name: Clang-Tidy Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Clang-Tidy
        run: sudo apt-get install clang-tidy -y

      - name: Run Clang-Tidy
        run: clang-tidy src/*.cpp -- -Iinclude
