name: Clang-Tidy Linting

on:
  push:
    branches:
      - main
      - Timer-Updates
  pull_request:
    branches:
      - main

jobs:
  lint-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Clang-Tidy
        run: choco install llvm

      - name: Run Clang-Tidy and Check for Warnings
        run: |
          chmod +x ./scripts/check_clang_tidy_warnings.sh
          ./scripts/check_clang_tidy_warnings.sh