name: Clang-Tidy Linting

on:
  push:
    branches:
      - main
      - Timer-Updates
  pull_request:
    branches:
      - main

jobs:
  lint-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Clang-Tidy
        run: choco install llvm

      - name: Run Clang-Tidy and Check for Warnings
        run: |
          $warnings = & clang-tidy.exe -p build *.cpp 2>&1
          if ($warnings) {
            Write-Output "Clang-Tidy found warnings:"
            Write-Output $warnings
            exit 1
          } else {
            Write-Output "No Clang-Tidy warnings found."
          }
        shell: powershell

      - name: Upload Clang-Tidy Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: clang-tidy-results
          path: clang-tidy-output.txt