name: Codacy Coverage Reporter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  codacy-coverage-reporter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake --no-progress -y
          choco install llvm --no-progress -y

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest -C Debug --output-on-failure

      - name: Generate coverage report
        run: |
          cd build
          # Adjust this command as needed to properly generate coverage.info
          llvm-cov gcov *.o > coverage.info

      - name: Check coverage file
        run: |
          cd build
          if (Test-Path coverage.info) {
            Write-Output "Coverage report generated successfully."
          } else {
            Write-Output "Coverage report not found."
            exit 1
          }

      - name: List files
        run: |
          Get-ChildItem -Recurse

      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build\coverage.info
