name: Codacy Coverage Reporter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  codacy-coverage-reporter:
    runs-on: windows-latest  # Use a Windows runner
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          choco install cmake --no-progress -y  # Install CMake using Chocolatey
          choco install llvm --no-progress -y   # Install LLVM for coverage reporting
          choco install git -y                  # Install Git to use Git Bash

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..
      
      - name: Build
        run: |
          cd build
          cmake --build .
      
      - name: Run tests
        run: |
          cd build
          ctest -C Debug --output-on-failure

      - name: Generate coverage report
        run: |
          cd build
          llvm-cov gcov *.o -o . > coverage.info   # Use llvm-cov as lcov equivalent

      - name: List files
        run: |
          dir /s build  # List files in the build directory to verify coverage report

      - name: Install Git Bash for Codacy
        shell: cmd
        run: |
          curl -Ls https://github.com/git-for-windows/git/releases/download/v2.39.1.windows.1/Git-2.39.1-64-bit.exe -o git-installer.exe
          start /wait git-installer.exe /VERYSILENT

      - name: Run Codacy Coverage Reporter
        shell: bash
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash -s report -r build/coverage.info
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
