name: CMakeBuild

on: [push, pull_request]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Debug

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@v3.28.1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}

      - name: Build with CMake
        run: cmake --build build --config ${{env.BUILD_CONFIGURATION}} --parallel

      - name: Install OpenCppCoverage
        run: |
          choco install OpenCppCoverage
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Run Tests and Generate Coverage Report
        shell: cmd
        run: |
          OpenCppCoverage --verbose --modules build${{env.BUILD_CONFIGURATION}}* --export_type cobertura:coverage.xml -- "build\Debug\Tempo.exe"

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
