name: Upload CodeCov Report

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: windows-latest
    name: Build, Test, Upload Code Coverage Report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'
        id: checkout_code

      - name: Setup CMake and add to PATH
        uses: github/setup-cmake@v3
        id: setup_cmake

      - name: Install OpenCppCoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build
        run: |
          cd build
          cmake --build . --config Debug

      - name: Run Tests with Coverage
        run: |
          cd build
          OpenCppCoverage.exe --sources=* --export_type cobertura:coverage.xml -- ctest -C Debug

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./build/coverage.xml
          fail_ci_if_error: true
