name: Codecov Coverage Report

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  codecov:
    runs-on: windows-latest  # Use a Windows runner
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install OpenCppCoverage
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
          
      - name: Configure CMake
        run: |
          run: cmake -B ${{github.workspace}}/build
          
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config 
          
      - name: Run tests
        run: |
          cd build
          ctest -C Debug --output-on-failure
          
      - name: Generate Coverage Report
        shell: cmd
        run: OpenCppCoverage --modules Debug --export_type cobertura:cmakeci.xml --cover_children -- ctest -C Debug --output-on-failure
          
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: cmakeci.xml
          token: ${{ secrets.CODECOV_TOKEN }}
