name: Codecov Coverage Report

on: [push, pull_request]

jobs:
  codecov:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenCppCoverage
        run: |
          choco install OpenCppCoverage

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Run Tests with Coverage
        run: |
          "C:/Program Files/OpenCppCoverage/OpenCppCoverage.exe" --sources Tempo --export_type cobertura:coverage.xml -- ctest -C Debug

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: build/coverage.xml
          fail_ci_if_error: true
