name: Codecov Coverage Report

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  codecov:
    runs-on: windows-latest  # Use a Windows runner
    steps:
    - uses: actions/checkout@v4

    - name: Install OpenCppCoverage
      run: |
        choco install OpenCppCoverage
        echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the Debug configuration
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Generate Coverage Report
      shell: cmd
      run: OpenCppCoverage --modules=* --export_type cobertura:cmakeci.xml --cover_children -- ctest -C Debug --test-dir build --output-on-failure

    - name: Upload Report to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        files: cmakeci.xml
        token: ${{ secrets.CODECOV_TOKEN }}
