name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
      - documentation
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure docs/html directory exists
        run: mkdir -p docs/html

      - name: Generate and deploy Doxygen docs
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          config_file: Doxyfile
          doxygen_version: 1.9.6
